version: 2

jobs:

  toxify:

      docker:
        - image: themattrix/tox

      parallelism: 3

      steps:
        
        - checkout

        - run: pip install tox

        - run: pip install pytest-circleci-parallelized

        - run: git clone https://github.com/qxf2/bitcoin-info.git

        - run: openssl aes-256-cbc -d -md sha256 -in ./conf/remote_credentials_enc.py -out ./conf/remote_credentials.py -pass env:KEY

        - run: tox --parallel--safe-build 

        - store_artifacts:
            path: ./screenshots
            destination: screenshots-file

        - store_artifacts:
            path: ./log
            destination: logs-file
        

workflows:
  version: 2

  myproj:
    jobs:
      - toxify