version: 2

jobs:

  # using tox
  toxify:

      docker:
        - image: circleci/python:3.7.0
  
      steps:
        
        - checkout

        - run: sudo pip install tox && tox

        - run: git clone https://github.com/qxf2/bitcoin-info.git

        - run: echo 'export app_path=/home/circleci/project/bitcoin-info/app/' >> $BASH_ENV

        - run: openssl aes-256-cbc -d -md sha256 -in ./conf/remote_credentials_enc.py -out ./conf/remote_credentials.py -pass env:KEY

        - run: python -m pytest -s -v -N "$app_path" -M Y --remote_project_name Qxf2_Selenium_POM --remote_build_name Selenium_Tutorial --junitxml=test-reports/junit.xml --tb=native
        

workflows:
  version: 2

  myproj:
    jobs:
      - toxify