version: 2.0
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    environment:
      TOXENV: circleci
    dependencies:
       pre:
         - pip install tox  

    steps:
      - checkout
      - run:
          name: Mobile app
          command: |
            git clone https://github.com/qxf2/bitcoin-info.git
      - run:
          name: Set Environment Variables
          command: |                      
            echo 'export app_path=/home/circleci/project/bitcoin-info/app/' >> $BASH_ENV  
      - run:
          name: Decrypt remote_credentials_enc.py using openssl
          command: |
            openssl aes-256-cbc -d -md sha256 -in ./conf/remote_credentials_enc.py -out ./conf/remote_credentials.py -pass env:KEY     

      - store_artifacts:
          path: ./screenshots
          destination: screenshots-file
      - store_artifacts:
          path: ./log
          destination: logs-file
    steps:
        override:
           -tox