version: 2

jobs:

  # using tox
  toxify:

      docker:
        - image: circleci/python:3.8.0

      steps:

        - checkout

        - run: sudo pip install tox && tox

workflows:
  version: 2

  myproj:
    jobs:
      - toxify