version: 2.0
jobs:
  build:
    docker:
      - image: themattrix/tox
    steps:
      - checkout
      - run:
          name: Run tox
          command: |
             tox

      - store_artifacts:
          path: ./screenshots
          destination: screenshots-file
      - store_artifacts:
          path: ./log
          destination: logs-file