version: 2

jobs:

  # using tox
  build:

      docker:
        - image: circleci/python:3.7.0
  
      steps:

        - checkout

        - run: echo 'export app_path=/home/circleci/project/bitcoin-info/app/' >> $BASH_ENV

        - run: openssl aes-256-cbc -d -md sha256 -in ./conf/remote_credentials_enc.py -out ./conf/remote_credentials.py -pass env:KEY

  
  toxify:

      docker:
        - image: circleci/python:3.7.0
        
      steps:

        - checkout

        - run: sudo pip install tox && tox

workflows:
  version: 2

  myproj:
    jobs:
      - build
      - toxify